-- 1. Xóa bảng để tránh lỗi (nếu có từ trước)
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS customers;

-- 2. Tạo bảng products
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price FLOAT8 NOT NULL,
    description TEXT,
    stock BIGINT DEFAULT 0
);

-- 3. Tạo bảng customers
CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone_number TEXT UNIQUE NOT NULL,
    zalo TEXT,
    registration_date TEXT
);

-- 4. Tạo bảng orders
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    amount FLOAT8 NOT NULL,
    status TEXT DEFAULT 'pending',
    payment_method TEXT DEFAULT 'auto',
    order_date TEXT
);

-- Dòng này dùng để vô hiệu hoá RLS (Row Level Security) tạm thời 
-- (Phù hợp cho dự án cá nhân đơn giản không Auth)
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
